### ISSUE TITLE
Stack trace when calling Vignette.tests if your test names are numbers

### ISSUE THREAD

**Issue by robd** [hayesgm/vignette#2]
I wanted to use a simple number for each experiment name. Vignette allows the following:

``` ruby
['whatever', 'options'].vignette(0)
```

but calling `Vignette.tests` then gives the following error: 

`undefined method 'to_sym' for 0:Fixnum`

```
.bundle/gems/ruby/2.2.0/gems/vignette-0.0.17/lib/vignette.rb:101:in `block in tests'
.bundle/gems/ruby/2.2.0/gems/vignette-0.0.17/lib/vignette.rb:101:in `each'
.bundle/gems/ruby/2.2.0/gems/vignette-0.0.17/lib/vignette.rb:101:in `map'
.bundle/gems/ruby/2.2.0/gems/vignette-0.0.17/lib/vignette.rb:101:in `tests'
```

Perhaps crash with IllegalArgument if the name is not a symbol : `[].vignette(name)`?

**Comment by hayesgm** [comment]
Handled this by converting to a string, then a symbol. You'll end up with `{:'0' => 'whatever'}` in `Vignette.tests`. Bumped to version 0.0.18 with this fix.

**Comment by robd** [comment]
:+1: makes sense - thanks!
